import Head from 'next/head'
import { Inter } from '@next/font/google'
import style from '@/styles/Home.module.css'
import { useEffect } from 'react'
import { Button } from '@mui/material'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
 const week = ["日", "月", "火", "水", "木", "金", "土"];
const today = new Date();

const showDate = new Date(today.getFullYear(), today.getMonth(),1);

  
  
useEffect(() => {

showProcess(today)
// eslint-disable-next-line react-hooks/exhaustive-deps
},[]);

function last(){
    showDate.setMonth(showDate.getMonth() - 1);
    showProcess(showDate);
    console.log(showDate)
}


function next(){
    showDate.setMonth(showDate.getMonth() + 1);
    showProcess(showDate);
    console.log("chip")
}


//Object.prototype.toString.call("button.next")
//showProcess(showDate);
function showProcess(date: Date) {
    const year = date.getFullYear();
    const month = date.getMonth();
    document.querySelector('#header')!.innerHTML = year + "年 " + (month + 1) + "月";

    let calendar = createProcess(year, month);
    document.querySelector('#calendar')!.innerHTML = calendar
};




  function createProcess(year: number, month: number) {
    let calendar = "<table><tr class='dayOfWeek'>";
    for (let i = 0; i < week.length; i++) {
        calendar += "<th>" + week[i] + "</th>";
    }
    calendar += "</tr>";

    let count = 0;
    let startDayOfWeek = new Date(year, month, 1).getDay();
    let endDate = new Date(year, month + 1, 0).getDate();
    let lastMonthEndDate = new Date(year, month, 0).getDate();
    let row = Math.ceil((startDayOfWeek + endDate) / week.length);

console.log(startDayOfWeek);
console.log(endDate)
console.log(lastMonthEndDate)
console.log(year)
console.log(month)

    for (let i = 0; i < row; i++) {
        calendar += "<tr>"
        for (let j = 0; j < week.length; j++) {
            if (i == 0 && j < startDayOfWeek) {
                calendar += "<td class='disabled'>" + (lastMonthEndDate - startDayOfWeek + j + 1) + "</td>";
            } else if (count >= endDate) {
                count++;
                calendar += "<td class='disabled'>" + (count - endDate) + "</td>";
            } else {
                count++;
                if(year == today.getFullYear()
                  && month == (today.getMonth())
                  && count == today.getDate()){
                    calendar += "<td class='today'>" + count + "</td>";
                } else {
                    calendar += "<td>" + count + "</td>";
                }
            }
        }
        calendar += "</tr>";
    }
    return calendar;
  }
 
 
 
 
  return (
    <>
      <Head>
        <title>Next Calendar App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <style></style>
    <div className="wrapper">
      <h1 id="header"></h1>

      <div id="next-last-btn">


       <Button variant="contained" id="last" onClick={last}>＜</Button>
       <Button variant="contained" id="next" onClick={next}>＞</Button>
      </div>
      <div id="calendar"></div>
    

    </div>

    </>
  )
}

