import Head from 'next/head'
import { Inter } from '@next/font/google'
import style from '@/styles/Home.module.css'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Calender App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <style></style>
    <div className="wrapper">
      <h1 id="header">2023 1</h1>

      <div id="next-last-btn">
        <button id="last" onClick={last}>＜</button>
       <button id="next" onClick={next}>＞</button>
      </div>
      <div id="calender"></div>
    <table></table>

    </div>

    </>
  )
}


const week = ["日", "月", "火", "水", "木", "金", "土"];
const today = new Date();

var showDate = new Date(today.getFullYear(), today.getMonth(),1);


function last(){
    showDate.setMonth(showDate.getMonth() - 1);
    showProcess(showDate);
    console.log(showDate)
}


function next(){
    showDate.setMonth(showDate.getMonth() + 1);
    showProcess(showDate);
    console.log("chip")
}
last();
next();
//Object.prototype.toString.call("button.next")

function showProcess(date: Date) {
    var year = date.getFullYear();
    var month = date.getMonth();
    //document.querySelector('#header')?.innerHTML = year + "年 " + (month + 1) + "月";

    var calendar = createProcess(year, month);
    //document.querySelector('#calendar').innerHTML = calendar;
}

  function createProcess(year: number, month: number) {
    var calendar = "<table><tr class='dayOfWeek'>";
    for (var i = 0; i < week.length; i++) {
        calendar += "<th>" + week[i] + "</th>";
    }
    calendar += "</tr>";

    var count = 0;
    var startDayOfWeek = new Date(year, month, 1).getDay();
    var endDate = new Date(year, month + 1, 0).getDate();
    var lastMonthEndDate = new Date(year, month, 0).getDate();
    var row = Math.ceil((startDayOfWeek + endDate) / week.length);

    for (var i = 0; i < row; i++) {
        calendar += "<tr>"
        for (var j = 0; j < week.length; j++) {
            if (i == 0 && j < startDayOfWeek) {
                calendar += "<td class='disabled'>" + (lastMonthEndDate - startDayOfWeek + j + 1) + "</td>";
            } else if (count >= endDate) {
                count++;
                calendar += "<td class='disabled'>" + (count - endDate) + "</td>";
            } else {
                count++;
                if(year == today.getFullYear()
                  && month == (today.getMonth())
                  && count == today.getDate()){
                    calendar += "<td class='today'>" + count + "</td>";
                } else {
                    calendar += "<td>" + count + "</td>";
                }
            }
        }
        calendar += "</tr>";
    }
    return calendar;
}